### ISSUE TITLE
Critical exploit: Cookie used to set XMR exchange rate

### ISSUE THREAD

**Issue by evantbyrne** [monero-integrations/monerowp#11]
The payment gateway class stores the exchange rate in `$_COOKIE['rate']`. Cookies can be modified by the HTTP client (web browser). This effectively allows customers to modify prices. To fix, remove the rate cookie altogether and store the exchange rate in the database or another server-side cache.

Source of exploit: https://github.com/monero-integrations/monerowp/blob/5d043b0150e1511e858f6825092161ec45fc099c/monero/include/monero_payments.php#L166

Cheers,

– Evan

**Comment by cryptochangements34** [comment]
First off, thanks for expressing your concern! Yes, this was a very obvious concern when deciding to store the exchange rate client side, as a result line 168 `if($xmr_live_price - $rate_cookie >= 1 || $xmr_live_price - $rate_cookie >= -1)` compares the actual live exchange rate against the exchange rate in the stored cookie so that if the difference changes by more than 1 fiat denomination (1 Euro, 1 Dollar, etc), either by market forces or by cookie editing, then the latest exchange rate will be used. Although this seems likea good solution to me, i am no security expert. I tested this solution against basic cookie editing, but if you can still manage to exploit this, please outline your process and the appropriate modifications can be made :)

**Comment by serhack** [comment]
Hello evan,
Sorry for late response. I'm at holiday now.
Thanks for discovering this security problem.

**Comment by serhack** [comment]
Solution proposed:
Store value on database

**Comment by cryptochangements34** [comment]
This issue should be fixed in Pull Request  #13 which gets rid of the cookie and instead stores the exchange rate data in the MySQL database used by WordPress.

**Comment by serhack** [comment]
I can confirm that. Thanks to @evantbyrne and @cryptochangements34, plugin is safer than yesterday
